import pandas as pd

# Problem 2 - Astram Event Data
print("=" * 80)
print("PROBLEM 2: ASTRAM EVENT DATA (Event-Driven Congestion)")
print("=" * 80)
df2 = pd.read_csv(r"dataset round2/Astram event data_anonymized - Astram event data_anonymizedb40ac87.csv", low_memory=False)
print(f"Shape: {df2.shape}")
print(f"\nColumns: {list(df2.columns)}")
print(f"\nDtypes:\n{df2.dtypes}")
print(f"\nNull counts:\n{df2.isnull().sum()}")
print(f"\nEvent types:\n{df2['event_type'].value_counts()}")
print(f"\nEvent causes:\n{df2['event_cause'].value_counts().head(20)}")
print(f"\nRequires road closure:\n{df2['requires_road_closure'].value_counts()}")
print(f"\nStatus:\n{df2['status'].value_counts()}")
print(f"\nCorridor:\n{df2['corridor'].value_counts().head(20)}")
print(f"\nPriority:\n{df2['priority'].value_counts()}")
print(f"\nVehicle types:\n{df2['veh_type'].value_counts().head(15)}")
print(f"\nPolice stations:\n{df2['police_station'].value_counts().head(20)}")
print(f"\nZones:\n{df2['zone'].value_counts().head(15)}")
print(f"\nJunctions:\n{df2['junction'].value_counts().head(15)}")
print(f"\nDate range: {df2['start_datetime'].min()} to {df2['start_datetime'].max()}")
print(f"\nLat range: {df2['latitude'].min()} to {df2['latitude'].max()}")
print(f"Lon range: {df2['longitude'].min()} to {df2['longitude'].max()}")
print(f"\nAuthenticated:\n{df2['authenticated'].value_counts()}")
print(f"\nDirection:\n{df2['direction'].value_counts().head(10)}")
